requireNamespace("usethis", quietly = TRUE)

knitr::purl("vignettes/data_cleaning_workbook.Rmd", "data-raw/build_data.R")
source("data-raw/build_data.R")

usethis::use_data(incident, overwrite = TRUE)
usethis::use_data(incident_contact_origin, overwrite = TRUE)
usethis::use_data(incident_subject_force_type, overwrite = TRUE)
usethis::use_data(incident_lighting, overwrite = TRUE)
usethis::use_data(incident_location_type, overwrite = TRUE)
usethis::use_data(incident_officer_injury_type, overwrite = TRUE)
usethis::use_data(incident_officer_medical_treatment, overwrite = TRUE)
usethis::use_data(incident_planned_contact, overwrite = TRUE)
usethis::use_data(incident_subject_action, overwrite = TRUE)
usethis::use_data(incident_subject_force_type, overwrite = TRUE)
usethis::use_data(incident_subject_injury, overwrite = TRUE)
usethis::use_data(incident_subject_medical_treatment, overwrite = TRUE)
usethis::use_data(incident_subject_perceived_condition, overwrite = TRUE)
usethis::use_data(incident_subject_resistance, overwrite = TRUE)
usethis::use_data(incident_subject_reason_not_arrested, overwrite = TRUE)
usethis::use_data(incident_type, overwrite = TRUE)
usethis::use_data(incident_video_type, overwrite = TRUE)
usethis::use_data(incident_weather, overwrite = TRUE)
usethis::use_data(officer_name_variants, overwrite = TRUE)
usethis::use_data(subject, overwrite = TRUE)
